name: Docker

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  docker-core:
    name: Build & Push Core
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Build Core image
        run: |
          docker build \
            -f bin/core/aio.Dockerfile \
            -t ghcr.io/pazerop/komodo-core:latest \
            -t ghcr.io/pazerop/komodo-core:${{ github.event.workflow_run.head_sha }} \
            .

      - name: Push Core image
        uses: wow-look-at-my/actions@ghcr-push#latest
        with:
          image: ghcr.io/pazerop/komodo-core:latest
          keep: 10

      - name: Push Core image (sha tag)
        shell: bash
        run: docker push "ghcr.io/pazerop/komodo-core:${{ github.event.workflow_run.head_sha }}"

  docker-periphery:
    name: Build & Push Periphery
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Build Periphery image
        run: |
          docker build \
            -f bin/periphery/aio.Dockerfile \
            -t ghcr.io/pazerop/komodo-periphery:latest \
            -t ghcr.io/pazerop/komodo-periphery:${{ github.event.workflow_run.head_sha }} \
            .

      - name: Push Periphery image
        uses: wow-look-at-my/actions@ghcr-push#latest
        with:
          image: ghcr.io/pazerop/komodo-periphery:latest
          keep: 10

      - name: Push Periphery image (sha tag)
        shell: bash
        run: docker push "ghcr.io/pazerop/komodo-periphery:${{ github.event.workflow_run.head_sha }}"
