name: Docker

on:
  push:

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-core:
    name: Build & Push Core
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: version
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - uses: wow-look-at-my/actions@ghcr#latest
        with:
          login: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          push_image: ghcr.io/pazerop/komodo-core:latest
          build_dockerfile: bin/core/aio.Dockerfile
          push: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          build_args: |
            KOMODO_BUILD_VERSION=${{ steps.version.outputs.short_sha }}

  docker-periphery:
    name: Build & Push Periphery
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: version
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - uses: wow-look-at-my/actions@ghcr#latest
        with:
          login: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          push_image: ghcr.io/pazerop/komodo-periphery:latest
          build_dockerfile: bin/periphery/aio.Dockerfile
          push: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          build_args: |
            KOMODO_BUILD_VERSION=${{ steps.version.outputs.short_sha }}
